### ISSUE TITLE
me sale something went wrong, hice todo correcto y puse localhost al connection.php

### ISSUE THREAD

**Issue by DEXUSGAMER** [Joxlyn/GDPS-Updates#1]
me sale something went wrong, hice todo correcto y puse localhost al connection.php pero me sigue saliendo igual porfavor ayudenme :(

**Comment by DEXUSGAMER** [comment]
ya lo solucione :V, puse la db name en password lol, lo siento por el tiempo xD

**Comment by Joxlyn** [comment]
Jaja xd
