### ISSUE TITLE
No carga

### ISSUE THREAD

**Issue by LOLROPS** [Joxlyn/GDPS-Updates#12]
Bueno la otra vez no me respondieron asi que pongo esto explicando mas detalladamente.
Basicamente cree un nuevo servidor pero apenas entro no puedo hacer la cuenta me dice "something went wrong" luego los cofres no cargan y no se pueden publicar niveles ya probe muchas cosas y espero que esta vez me den una solucion

**Comment by CR700GD** [comment]
haz echo algo mal
