### ISSUE TITLE
Error on serverinfo.php

### ISSUE THREAD

**Issue by tzt345** [Joxlyn/GDPS-Updates#14]
@Joxlyn 
![Screenshot_2021-05-29-22-25-59-20](https://user-images.githubusercontent.com/83703996/120073925-0767bd80-c0cd-11eb-9ac3-1e469b84a3ac.png)

**Comment by Joxlyn** [comment]
Hi!
This error can occur for various reasons:

1) Host sends incompatibility error messages
2) The version of php you have does not support these .php files
3) Some files cannot be found

Try to check if the files are well located, re-upload the .php files or if you have the possibility to hide these errors then do it.

**Comment by tzt345** [comment]
> Hi!
> This error can occur for various reasons:
> 
> 1. Host sends incompatibility error messages
> 2. The version of php you have does not support these .php files
> 3. Some files cannot be found
> 
> Try to check if the files are well located, re-upload the .php files or if you have the possibility to hide these errors then do it.

I have literally a php version the php version is: 7.0.19
@Joxlyn

**Comment by RXNationGMG** [comment]
@Joxlyn ik know because the style.php & navigation.php wasn't created In incl you need to make that 2

**Comment by Joxlyn** [comment]
@RobloxNationGaming @tzt345 Excellent observation, I already updated most of the files that depended on style.php and navigation.php. Try again to load the new files and it will tell me if the problem disappeared :)

**Comment by tzt345** [comment]
> @RobloxNationGaming @tzt345 Excellent observation, I already updated most of the files that depended on style.php and navigation.php. Try again to load the new files and it will tell me if the problem disappeared :)

`ok it worked!`

> & Btw can you make a custom creator points like the gdopenserver plz!

**Comment by Joxlyn** [comment]
@tzt345 I have no plans to add the custom creator points or any other function, possibly in the future I will.
