### ISSUE TITLE
Para Moderador/For Moderator

### ISSUE THREAD

**Issue by Joxlyn** [Joxlyn/GDPS-Updates#4]
ESPAÑOL:
Con la más reciente actualización de mis PHP (04/12/2017, no contando la del dia de hoy 05/12/2017), Los comandos que utilizan los Moderadores (Elder y Normal) ahora no dependeran del isAdmin, Para poder hacer esto funcionar se necesita hacer lo siguiente:
-Crear un rol nombrandolo a Moderador (Ya sea Elder o Normal)
-Dejar en blanco el RoleID
-Cambiar en Prioritario a 1
-Cambiar (Segun tu tipo de moderador) las columnas de Comando estrellas, featured y todo eso a 1.
-Para que se active el modo moderador, Nombrar en actionRequestMod a 1 (Eso quiere decir que 1= Activo y 0= No activo).
-Dejar en 0 la columna de predeterminado.
-Agregar un color (Formato R,G,B) para tener los textos de colores.
-Para el simbolo de mod, es cambiar el modBadge a 1 o 2 (0=Ningun simbolo, 1=Moderador Normal y 2=Moderador Elder).
-Agregar el rol despues de crearlo
Ahora para poder activar o asignar el rol a la persona deseada es hacer lo siguiente:
-Copiar la RoleID generada
-Copiar el AccountID de la persona a la que se le dara mod,
-Ir a roleassing y crear una casilla
-Dejar en blanco la ID (la primera columna)
-Pegar la RoleID de tu rol creado
-Pegar la AccountID
-Terminar y guardar el roleassing
-Listo, ahora ve a tu GDPS, ve a ajustes, ayuda y da en REQ, y listo ya eres Moderador!.
Cualquier pregunta dejarla en: https://github.com/Joxlyn/GDPS-Updates/issues
~Joxlyn~
ENGLISH:
With the most recent update of my PHP (04/12/2017, not counting today's 05/12/2017), the commands used by the Moderators (Elder and Normal) now will not depend on isAdmin, to be able to do this work, you need to do the following:
-Create a role naming it Moderator (Either Elder or Normal)
-Leave the RoleID blank
-Change to Priority 1
-Change (According to your type of moderator) the columns of Commando stars, featured and all that to 1.
-To activate the moderator mode, Name in actionRequestMod a 1 (That means that 1 = Active and 0 = Not active).
-Leave the default column at 0.
-Add a color (Format R, G, B) to have the colored texts.
-For the mod symbol, it is to change the modBadge to 1 or 2 (0 = No symbol, 1 = Normal Moderator and 2 = Elder Moderator).
-Add the role after creating it
Now to activate or assign the role to the desired person is to do the following:
-Copying the RoleID generated
-Copy the AccountID of the person who will be given mod,
-Go to roleassing and create a box
-Leave the ID blank (the first column)
-Press the RoleID of your created role
-Pay the AccountID
-Finish and save the roleassing
-Ready, now go to your GDPS, go to adjustments, help and give in REQ, and you are ready to be Moderator !.
Any question leave it at: https://github.com/Joxlyn/GDPS-Updates/issues
~Joxlyn~

**Comment by CR700GD** [comment]
como puedo modificar los colores cuando pongo un post en mi perfil

**Comment by CR700GD** [comment]
como robtop

**Comment by dewyisqt** [comment]
@CR700GD du musst in der Datenbank in den Table mit dem Namen "accounts" und die AccountID deines Accounts zu 71 ändern
