### ISSUE TITLE
Problema con los codigos de colores.

### ISSUE THREAD

**Issue by PanbimboGD1** [Joxlyn/GDPS-Updates#5]
Cuando inserto un codigo de color "html" a un rol y ese rol se lo doy a un usuario, ese usuario pasa a escribir en blanco, independientemente del color que le pongas. Como podría solucionar esto? Gracias de antemano.

**Comment by Joxlyn** [comment]
Hola! Para que el usuario pueda escribir con un color diferente, debes de insertar el color en Formato R,G,B.

**Comment by PanbimboGD1** [comment]
Inserté el formato R,G.B. Por ejemplo, al intentar insertar el color cyan escribiría esto verdad? (0,255,255)

**Comment by Joxlyn** [comment]
Si

**Comment by PanbimboGD1** [comment]
Pero lo hice con formato R.G.B y seguía sin ir... que puedo hacer?

**Comment by Joxlyn** [comment]
Ya has asignado el rol a una persona?

**Comment by PanbimboGD1** [comment]
Si, y cuando escriben, escriben en blanco.

**Comment by Joxlyn** [comment]
Has actualizado tu database y tus archivos PhP a los actuales?

**Comment by PanbimboGD1** [comment]
Si. mi version actual de mySQL es "MySQL 5.5" y creo que he hecho todo correctamente, pero sigo sin entender el fallo. Además estoy haciendo lo que viene siendo un proyecto gordo, lo puedes ver en "http://panesgdps.com", y necesito tenerlo arreglado, ya que vamos a tener un rango "Vip" y si su chat no tiene un color personalizado no se va a distinguir el rango del resto de usuarios normales.

**Comment by Joxlyn** [comment]
No pero yo digo los archivos php que añadiste a tu FTP Manager

**Comment by PanbimboGD1** [comment]
A que te refieres? A mi FTP Manager añadí los archivos que tu proporcionaste, entre los que se encontraban el "database.sql". Puedes ver que la base de datos está subida en "http://panesgdps.com/database" y las tools se encuentran en "http://panesgdps.com/database/tools/"

**Comment by Joxlyn** [comment]
Vale tienes discord? Si tienes mandame mensaje por privado para mas ayuda!! #6557

**Comment by PanbimboGD1** [comment]
Listo, me llamo Panbimbo [GD], te he agregado.

**Comment by PanbimboGD1** [comment]
Todo solucionado, aparentemente era un error mío mas simple de lo que pensaba. El soporte del developer excelente, gracias :+1:

**Comment by Joxlyn** [comment]
De nada :)

**Comment by xXFireBlastXx** [comment]
De nada :)
