### ISSUE TITLE
como modificar las estadisticas de una cuenta

### ISSUE THREAD

**Issue by CR700GD** [Joxlyn/GDPS-Updates#6]
Como puedo modificar las estadisticas de mi cuenta para que tenga lo que agrege

**Comment by Joxlyn** [comment]
Lo siento, pero no puedes modificar tus estadisticas, solo harias un efecto visual (Cuando busques tu perfil , tenga lo que agregaste), y cuando inicies sesión se eliminen.

**Comment by CR700GD** [comment]
Y modificar los cofres :'v
