### ISSUE TITLE
Hay algun tutorial de como usar los roles etc..? (porque no entiendo lo que explicaron xd :v)

### ISSUE THREAD

**Issue by SirGaboYT** [Joxlyn/GDPS-Updates#7]

**Comment by Joxlyn** [comment]
Xd Entra a esta pagina! Ahi lo explican mejor xd https://ayudagdps.wordpress.com/2018/01/06/2-como-hacer-el-rol-de-elder-mods-y-normal-mods-y-como-ponertelo/
