### ISSUE TITLE
Quest Crashean mi server

### ISSUE THREAD

**Issue by CR700GD** [Joxlyn/GDPS-Updates#8]
Hola las queso Al querer verlas me Crashean mi server varios de mis mods me han reportado este error como lo soluciono

**Comment by CR700GD** [comment]
Quest*

**Comment by Joxlyn** [comment]
@CR700GD Supongo que ya encontraste solución pero igualmente lo respondo, debes de crear al menos 3 Quests de cada tipo para que el juego reconozca que hay Quests, si no lo hace automáticamente el juego crasheara.
