### ISSUE TITLE
Error en comentarios con colores

### ISSUE THREAD

**Issue by nightspeed** [Joxlyn/GDPS-Updates#9]
tengo el commentColor en 255,128,000 (anaranjado) y al comentar un nivel sale en amarillo.
y como hago para que los comentarios en el perfil salgan de colores como robtop.

**Comment by Joxlyn** [comment]
Hola! ¿Has probado con otros colores? 
Para que tengas las letras azules, ve a tu database (Base de datos), busca accounts y busca tu cuenta, luego en accountID pon 71, luego ve a tu gdps, da en refresh login y listo!

**Comment by nightspeed** [comment]
Y no se puede cambiar el color de azul a otro por ejemplo anaranjado

2018-01-17 13:21 GMT-04:30 xXFireBlastXx <notifications@github.com>:

**Comment by Joxlyn** [comment]
@nightspeed Debes de editar el codigo de los archivos
